name: Merge main into beta
on:
  push:
    branches:
      - main
jobs:
  merge:
    name: Merge main into beta
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: beta
      - name: Merge repository
        run: |
          git config user.name "github-actions-bot"
          git config user.email "support+actions@github.com"
          git fetch
          git merge origin/main --allow-unrelated-histories
          git push